# Generated by Django 6.1 on 2026-09-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedata', '0005_alter_moves_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learnset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('moves', models.JSONField()),
                ('species_id', models.IntegerField(unique=True)),
            ],
        ),
    ]
